version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp
      POSTGRES_DB: erp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://erp:erp@db:5432/erp?schema=public
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
volumes:
  db-data:






